### ISSUE TITLE
Question about "Node-Pair Neighborhood Encoder"

### ISSUE THREAD

**Issue by Walker-ZD** [zhitao-wang/PLNLP#1]
Thanks for your brilliant work about PLNLP.  In the paper "Pairwise Learning for Neural Link Prediction", there exists the application of "Node-Pair Neighborhood Encoder" module, which is used to encode the subgraph corresponding to the target link. It seems that the project does not implement this module, is it because its effect is not obvious? Or is it too inefficient to run? Thank you.

**Comment by zhitao-wang** [comment]
Thanks for your question. 

Yes, it is inefficient to run the Node-Pair Neighborhood Encoder. We are looking for a more efficient way for implementation.
